
 const ATypes= {
  SET_USER: 'SET_USER',
  SERVER_QUESTION_DATA: 'SERVER_QUESTION_DATA',
  SERVER_GAME_DATA: 'SERVER_GAME_DATA', 
  CHART_DATA:'CHART_DATA',
  SET_BEST_PLAYERS: 'SET_BEST_PLAYERS'

 }

 export default ATypes